### PR TITLE
new dictionaries 

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by michaeldimimu** [comment]
Wonderful stuff. I see you added a new Japanese dictionary file.
However, I'll need you to delete the` japanese_dictionary.py` file and put it in the `dictionaries.py` file

Also, we're to convert from the respective language to English, and not the other way around (not quite sure how convenient that will be to do with Japanese 😢)

**Comment by ghost** [comment]
Got it and thx 😁

**Comment by michaeldimimu** [comment]
Nice work bro

**Comment by ghost** [comment]
> Nice work bro

Thanks

**Pull request merged**
